### PR TITLE
Add README for Pull Request and Code Review checklist

### PR DESCRIPTION
**Pull request by hepnerthomas**
feat: pull request and code review checklist documentation.

Trello Ticket: 
https://trello.com/c/GP5cUAHV/11-pull-requests-build-checklist-for-feature-branch-workflow-s

### CODE REVIEW

**Review by allanviguilla — CHANGES_REQUESTED** [review]
Great demo Thomas

**Review by amberlyM — CHANGES_REQUESTED** [review]
This looks horrible. Do better.

**Review by qzyan — CHANGES_REQUESTED** [review]
Figure out how to make md

**Review by amberlyM — APPROVED** [review]
looks great!
@allanviguilla  and @qzyan : please review

**Review by qzyan — APPROVED** [review]
Looks good!

**Review by allanviguilla — APPROVED** [review]
Great work

**Pull request merged**
